import type { MetadataRoute } from "next";
import { siteConfig } from "@/config/site";

export default function robots(): MetadataRoute.Robots {
  const baseUrl = siteConfig.url;

  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/features",
          "/solutions",
          "/pricing",
          "/developers",
          "/docs",
          "/security",
          "/status",
          "/blog",
          "/contact",
          "/privacy",
          "/terms",
          "/cookies",
          "/p/",
          "/brand/",
        ],
        disallow: [
          "/login",
          "/signup",
          "/signin",
          "/register",
          "/onboarding",
          "/invite/",
          "/api/",
          "/*/*/analytics",
          "/*/*/billing",
          "/*/*/brain",
          "/*/*/brand",
          "/*/*/campaigns",
          "/*/*/developers",
          "/*/*/guardian",
          "/*/*/members",
          "/*/*/qr",
          "/*/*/routes",
          "/*/*/settings",
          "/*/*/teams",
          "/*/*/invitations",
          "/*/*/audit",
          "/*/*/approvals",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: [
          "/",
          "/features",
          "/solutions",
          "/pricing",
          "/developers",
          "/docs",
          "/security",
          "/status",
          "/blog",
          "/contact",
          "/privacy",
          "/terms",
          "/cookies",
          "/p/",
          "/brand/",
        ],
        disallow: [
          "/login",
          "/signup",
          "/signin",
          "/register",
          "/onboarding",
          "/invite/",
          "/api/",
          "/*/*/analytics",
          "/*/*/billing",
          "/*/*/brain",
          "/*/*/brand",
          "/*/*/campaigns",
          "/*/*/developers",
          "/*/*/guardian",
          "/*/*/members",
          "/*/*/qr",
          "/*/*/routes",
          "/*/*/settings",
          "/*/*/teams",
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
