import { QrContentV1 } from "./schema";

export type QrCategory =
  | "all"
  | "quick_start"
  | "web"
  | "social"
  | "communication"
  | "business"
  | "productivity"
  | "commerce"
  | "payments"
  | "files";

export interface QrTypeDefinition {
  id: string;
  contentType: QrContentV1["type"];
  label: string;
  shortDescription: string;
  category: QrCategory;
  iconName: string;
  platform?: string;
  prefixUrl?: string;
  placeholder?: string;
  keywords: string[];
  supportsDynamic: boolean;
  supportsStatic: boolean;
  createDefault: () => QrContentV1;
}

export const QR_CATEGORIES: { id: QrCategory; label: string }[] = [
  { id: "all", label: "All Types" },
  { id: "quick_start", label: "Quick Start" },
  { id: "web", label: "Web & Links" },
  { id: "social", label: "Social" },
  { id: "communication", label: "Contact & Comm" },
  { id: "business", label: "Business" },
  { id: "productivity", label: "Productivity" },
  { id: "commerce", label: "Commerce" },
  { id: "payments", label: "Payments" },
  { id: "files", label: "Files & Documents" },
];

export const QR_TYPE_REGISTRY: Record<string, QrTypeDefinition> = {
  // ==========================================
  // CORE / FOUNDATIONAL TYPES
  // ==========================================
  url: {
    id: "url",
    contentType: "url",
    label: "Website URL",
    shortDescription: "Redirect to any website, landing page, or online portal.",
    category: "web",
    iconName: "Globe",
    keywords: ["url", "website", "link", "web", "http", "https"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "url",
      url: "",
      isDynamic: true,
    }),
  },
  text: {
    id: "text",
    contentType: "text",
    label: "Plain Text",
    shortDescription: "Display formatted text or code offline without requiring internet.",
    category: "quick_start",
    iconName: "FileText",
    keywords: ["text", "note", "message", "offline", "raw"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "text",
      text: "",
    }),
  },
  wifi: {
    id: "wifi",
    contentType: "wifi",
    label: "Wi-Fi Access",
    shortDescription: "Connect guest devices to a Wi-Fi network instantly.",
    category: "quick_start",
    iconName: "Wifi",
    keywords: ["wifi", "network", "internet", "ssid", "wireless"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "wifi",
      ssid: "",
      security: "WPA",
      password: "",
      hidden: false,
    }),
  },
  vcard: {
    id: "vcard",
    contentType: "vcard",
    label: "Contact Card (vCard)",
    shortDescription: "Digital business card saved straight into phone address book.",
    category: "communication",
    iconName: "Contact",
    keywords: ["vcard", "contact", "person", "address", "card", "business card"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "vcard",
      firstName: "",
      lastName: "",
      organization: "",
      jobTitle: "",
      phone: "",
      mobile: "",
      email: "",
      website: "",
      address: "",
      note: "",
    }),
  },
  app: {
    id: "app",
    contentType: "app",
    label: "Smart App Link",
    shortDescription: "Auto-detect iOS / Android device and redirect to store.",
    category: "web",
    iconName: "Smartphone",
    keywords: ["app", "ios", "android", "play store", "app store"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "app",
      appName: "",
      iosUrl: "",
      androidUrl: "",
      fallbackUrl: "",
    }),
  },
  file: {
    id: "file",
    contentType: "file",
    label: "Document / File",
    shortDescription: "Share documents, menus, or archives hosted on Cloudflare R2.",
    category: "files",
    iconName: "FileSpreadsheet",
    keywords: ["file", "document", "upload", "r2", "asset"],
    supportsDynamic: true,
    supportsStatic: false,
    createDefault: () => ({
      type: "file",
      assetId: "",
      fileName: "",
      fileSize: 0,
      mimeType: "application/octet-stream",
      downloadUrl: "",
    }),
  },
  pdf: {
    id: "pdf",
    contentType: "file",
    label: "PDF Document",
    shortDescription: "Distribute brochures, menus, or whitepapers in PDF format.",
    category: "files",
    iconName: "FileText",
    keywords: ["pdf", "brochure", "menu", "whitepaper", "document"],
    supportsDynamic: true,
    supportsStatic: false,
    createDefault: () => ({
      type: "file",
      assetId: "",
      fileName: "",
      fileSize: 0,
      mimeType: "application/pdf",
      downloadUrl: "",
    }),
  },
  email: {
    id: "email",
    contentType: "email",
    label: "Send Email",
    shortDescription: "Pre-fill recipient email, subject line, and draft message.",
    category: "communication",
    iconName: "Mail",
    keywords: ["email", "mail", "mailto", "message", "inbox"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "email",
      recipient: "",
      subject: "",
      body: "",
    }),
  },
  phone: {
    id: "phone",
    contentType: "phone",
    label: "Call Phone",
    shortDescription: "Prompt scanner device to dial a customer service or direct number.",
    category: "communication",
    iconName: "Phone",
    keywords: ["phone", "call", "tel", "telephone", "dial"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "phone",
      phoneNumber: "",
    }),
  },
  sms: {
    id: "sms",
    contentType: "sms",
    label: "Send SMS",
    shortDescription: "Trigger SMS text message with preset recipient and draft text.",
    category: "communication",
    iconName: "MessageSquare",
    keywords: ["sms", "text message", "txt"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "sms",
      phoneNumber: "",
      message: "",
    }),
  },
  location: {
    id: "location",
    contentType: "location",
    label: "Location / Map",
    shortDescription: "Pinpoint GPS coordinates on Google Maps or Apple Maps.",
    category: "business",
    iconName: "MapPin",
    keywords: ["location", "map", "gps", "coordinates", "place"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "location",
      latitude: 0,
      longitude: 0,
      label: "",
    }),
  },
  calendar: {
    id: "calendar",
    contentType: "calendar",
    label: "Calendar Event",
    shortDescription: "Add conference, webinar, or meeting directly to device calendar.",
    category: "business",
    iconName: "Calendar",
    keywords: ["calendar", "event", "schedule", "meeting", "vevent"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "calendar",
      title: "",
      startDate: new Date().toISOString().slice(0, 16),
      endDate: new Date(Date.now() + 3600000).toISOString().slice(0, 16),
      location: "",
      description: "",
    }),
  },

  // ==========================================
  // SOCIAL PLATFORMS
  // ==========================================
  instagram: {
    id: "instagram",
    contentType: "platform_link",
    platform: "instagram",
    label: "Instagram",
    shortDescription: "Link to profile, brand handle, or latest Instagram reel.",
    category: "social",
    iconName: "Instagram",
    prefixUrl: "https://instagram.com/",
    placeholder: "yourusername",
    keywords: ["instagram", "ig", "insta", "reels", "meta", "social"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "instagram",
      targetUrl: "https://instagram.com/",
      username: "",
      isDynamic: true,
    }),
  },
  youtube: {
    id: "youtube",
    contentType: "platform_link",
    platform: "youtube",
    label: "YouTube",
    shortDescription: "Link to YouTube channel, livestream, or specific video.",
    category: "social",
    iconName: "Youtube",
    prefixUrl: "https://youtube.com/@",
    placeholder: "channelname",
    keywords: ["youtube", "yt", "video", "channel", "google"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "youtube",
      targetUrl: "https://youtube.com/",
      username: "",
      isDynamic: true,
    }),
  },
  linkedin: {
    id: "linkedin",
    contentType: "platform_link",
    platform: "linkedin",
    label: "LinkedIn",
    shortDescription: "Connect professional profile, company page, or job board.",
    category: "social",
    iconName: "Linkedin",
    prefixUrl: "https://linkedin.com/in/",
    placeholder: "profile-slug",
    keywords: ["linkedin", "career", "professional", "company", "jobs"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "linkedin",
      targetUrl: "https://linkedin.com/",
      username: "",
      isDynamic: true,
    }),
  },
  tiktok: {
    id: "tiktok",
    contentType: "platform_link",
    platform: "tiktok",
    label: "TikTok",
    shortDescription: "Drive traffic to your TikTok creator profile or viral post.",
    category: "social",
    iconName: "Share2",
    prefixUrl: "https://tiktok.com/@",
    placeholder: "creator",
    keywords: ["tiktok", "video", "viral", "short"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "tiktok",
      targetUrl: "https://tiktok.com/",
      username: "",
      isDynamic: true,
    }),
  },
  x_twitter: {
    id: "x_twitter",
    contentType: "platform_link",
    platform: "x_twitter",
    label: "X (Twitter)",
    shortDescription: "Direct users to follow your account or view a post on X.",
    category: "social",
    iconName: "Twitter",
    prefixUrl: "https://x.com/",
    placeholder: "handle",
    keywords: ["x", "twitter", "tweet", "post"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "x_twitter",
      targetUrl: "https://x.com/",
      username: "",
      isDynamic: true,
    }),
  },
  whatsapp: {
    id: "whatsapp",
    contentType: "platform_link",
    platform: "whatsapp",
    label: "WhatsApp",
    shortDescription: "Open instant WhatsApp chat with predefined welcome text.",
    category: "social",
    iconName: "MessageCircle",
    prefixUrl: "https://wa.me/",
    placeholder: "15550199",
    keywords: ["whatsapp", "wa", "chat", "message"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "whatsapp",
      targetUrl: "https://wa.me/",
      username: "",
      isDynamic: true,
    }),
  },
  telegram: {
    id: "telegram",
    contentType: "platform_link",
    platform: "telegram",
    label: "Telegram",
    shortDescription: "Join Telegram community channel, announcement group, or bot.",
    category: "social",
    iconName: "Send",
    prefixUrl: "https://t.me/",
    placeholder: "channel_name",
    keywords: ["telegram", "tg", "channel", "group"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "telegram",
      targetUrl: "https://t.me/",
      username: "",
      isDynamic: true,
    }),
  },
  discord: {
    id: "discord",
    contentType: "platform_link",
    platform: "discord",
    label: "Discord",
    shortDescription: "Invite gamers and community members to your Discord server.",
    category: "social",
    iconName: "Users",
    prefixUrl: "https://discord.gg/",
    placeholder: "invite-code",
    keywords: ["discord", "server", "community", "gaming"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "discord",
      targetUrl: "https://discord.gg/",
      username: "",
      isDynamic: true,
    }),
  },
  snapchat: {
    id: "snapchat",
    contentType: "platform_link",
    platform: "snapchat",
    label: "Snapchat",
    shortDescription: "Add friends or promote public profile on Snapchat.",
    category: "social",
    iconName: "Camera",
    prefixUrl: "https://snapchat.com/add/",
    placeholder: "username",
    keywords: ["snapchat", "snap", "lens"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "snapchat",
      targetUrl: "https://snapchat.com/add/",
      username: "",
      isDynamic: true,
    }),
  },
  twitch: {
    id: "twitch",
    contentType: "platform_link",
    platform: "twitch",
    label: "Twitch",
    shortDescription: "Promote your live gaming or creative broadcast on Twitch.",
    category: "social",
    iconName: "Tv",
    prefixUrl: "https://twitch.tv/",
    placeholder: "streamer",
    keywords: ["twitch", "stream", "live", "broadcast"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "twitch",
      targetUrl: "https://twitch.tv/",
      username: "",
      isDynamic: true,
    }),
  },
  pinterest: {
    id: "pinterest",
    contentType: "platform_link",
    platform: "pinterest",
    label: "Pinterest",
    shortDescription: "Share visual moodboard, product pins, or creator profile.",
    category: "social",
    iconName: "Pin",
    prefixUrl: "https://pinterest.com/",
    placeholder: "board-name",
    keywords: ["pinterest", "pin", "moodboard", "fashion"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "pinterest",
      targetUrl: "https://pinterest.com/",
      username: "",
      isDynamic: true,
    }),
  },
  reddit: {
    id: "reddit",
    contentType: "platform_link",
    platform: "reddit",
    label: "Reddit",
    shortDescription: "Link to subreddit community, AMA discussion, or post.",
    category: "social",
    iconName: "MessageSquare",
    prefixUrl: "https://reddit.com/r/",
    placeholder: "community",
    keywords: ["reddit", "subreddit", "ama", "forum"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "reddit",
      targetUrl: "https://reddit.com/",
      username: "",
      isDynamic: true,
    }),
  },
  threads: {
    id: "threads",
    contentType: "platform_link",
    platform: "threads",
    label: "Threads",
    shortDescription: "Connect directly to your Instagram Threads conversation feed.",
    category: "social",
    iconName: "AtSign",
    prefixUrl: "https://threads.net/@",
    placeholder: "username",
    keywords: ["threads", "meta", "microblog"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "threads",
      targetUrl: "https://threads.net/",
      username: "",
      isDynamic: true,
    }),
  },
  facebook: {
    id: "facebook",
    contentType: "platform_link",
    platform: "facebook",
    label: "Facebook",
    shortDescription: "Link to company page, private group, or event on Facebook.",
    category: "social",
    iconName: "Facebook",
    prefixUrl: "https://facebook.com/",
    placeholder: "page-slug",
    keywords: ["facebook", "fb", "meta"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "facebook",
      targetUrl: "https://facebook.com/",
      username: "",
      isDynamic: true,
    }),
  },
  messenger: {
    id: "messenger",
    contentType: "platform_link",
    platform: "messenger",
    label: "Messenger",
    shortDescription: "Open a direct Facebook Messenger customer support window.",
    category: "social",
    iconName: "MessageCircle",
    prefixUrl: "https://m.me/",
    placeholder: "username",
    keywords: ["messenger", "meta", "chat"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "messenger",
      targetUrl: "https://m.me/",
      username: "",
      isDynamic: true,
    }),
  },
  wechat: {
    id: "wechat",
    contentType: "platform_link",
    platform: "wechat",
    label: "WeChat",
    shortDescription: "Link to WeChat public account or personal contact URL.",
    category: "social",
    iconName: "MessageSquare",
    prefixUrl: "https://weixin.qq.com/",
    placeholder: "account",
    keywords: ["wechat", "weixin", "china"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "wechat",
      targetUrl: "https://weixin.qq.com/",
      username: "",
      isDynamic: true,
    }),
  },
  signal: {
    id: "signal",
    contentType: "platform_link",
    platform: "signal",
    label: "Signal",
    shortDescription: "End-to-end encrypted chat link on Signal messenger.",
    category: "social",
    iconName: "Shield",
    prefixUrl: "https://signal.me/#p/",
    placeholder: "username",
    keywords: ["signal", "private", "encrypted"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "signal",
      targetUrl: "https://signal.me/",
      username: "",
      isDynamic: true,
    }),
  },

  // ==========================================
  // MEDIA & STREAMING
  // ==========================================
  spotify: {
    id: "spotify",
    contentType: "platform_link",
    platform: "spotify",
    label: "Spotify",
    shortDescription: "Open album, playlist, podcast episode, or artist profile.",
    category: "web",
    iconName: "Music",
    prefixUrl: "https://open.spotify.com/",
    placeholder: "track/...",
    keywords: ["spotify", "music", "podcast", "audio"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "spotify",
      targetUrl: "https://open.spotify.com/",
      username: "",
      isDynamic: true,
    }),
  },
  soundcloud: {
    id: "soundcloud",
    contentType: "platform_link",
    platform: "soundcloud",
    label: "SoundCloud",
    shortDescription: "Stream tracks or DJ sets hosted on SoundCloud.",
    category: "web",
    iconName: "Headphones",
    prefixUrl: "https://soundcloud.com/",
    placeholder: "artist/track",
    keywords: ["soundcloud", "music", "dj", "audio"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "soundcloud",
      targetUrl: "https://soundcloud.com/",
      username: "",
      isDynamic: true,
    }),
  },
  vimeo: {
    id: "vimeo",
    contentType: "platform_link",
    platform: "vimeo",
    label: "Vimeo",
    shortDescription: "Direct viewers to high-definition video portfolios on Vimeo.",
    category: "web",
    iconName: "Video",
    prefixUrl: "https://vimeo.com/",
    placeholder: "video-id",
    keywords: ["vimeo", "video", "cinema", "film"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "vimeo",
      targetUrl: "https://vimeo.com/",
      username: "",
      isDynamic: true,
    }),
  },

  // ==========================================
  // BUSINESS & REVIEWS
  // ==========================================
  google_business: {
    id: "google_business",
    contentType: "platform_link",
    platform: "google_business",
    label: "Google Business Review",
    shortDescription: "Encourage patrons to write 5-star Google reviews instantly.",
    category: "business",
    iconName: "Star",
    prefixUrl: "https://g.page/r/",
    placeholder: "place-id/review",
    keywords: ["google", "reviews", "rating", "business", "feedback"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "google_business",
      targetUrl: "https://g.page/",
      username: "",
      isDynamic: true,
    }),
  },
  tripadvisor: {
    id: "tripadvisor",
    contentType: "platform_link",
    platform: "tripadvisor",
    label: "TripAdvisor",
    shortDescription: "Direct guests to your restaurant or hotel TripAdvisor listing.",
    category: "business",
    iconName: "Compass",
    prefixUrl: "https://tripadvisor.com/",
    placeholder: "Hotel_Review-...",
    keywords: ["tripadvisor", "travel", "hotel", "restaurant"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "tripadvisor",
      targetUrl: "https://tripadvisor.com/",
      username: "",
      isDynamic: true,
    }),
  },
  yelp: {
    id: "yelp",
    contentType: "platform_link",
    platform: "yelp",
    label: "Yelp",
    shortDescription: "Promote local dining reviews and check-ins on Yelp.",
    category: "business",
    iconName: "Search",
    prefixUrl: "https://yelp.com/biz/",
    placeholder: "business-name",
    keywords: ["yelp", "local", "reviews", "food"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "yelp",
      targetUrl: "https://yelp.com/biz/",
      username: "",
      isDynamic: true,
    }),
  },
  calendly: {
    id: "calendly",
    contentType: "platform_link",
    platform: "calendly",
    label: "Calendly Booking",
    shortDescription: "Allow clients to schedule a consultation or discovery call.",
    category: "business",
    iconName: "Clock",
    prefixUrl: "https://calendly.com/",
    placeholder: "username/30min",
    keywords: ["calendly", "booking", "schedule", "calendar", "appointment"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "calendly",
      targetUrl: "https://calendly.com/",
      username: "",
      isDynamic: true,
    }),
  },
  zoom: {
    id: "zoom",
    contentType: "platform_link",
    platform: "zoom",
    label: "Zoom Meeting",
    shortDescription: "Launch directly into a recurring Zoom conference room.",
    category: "business",
    iconName: "Video",
    prefixUrl: "https://zoom.us/j/",
    placeholder: "meeting-id",
    keywords: ["zoom", "meeting", "call", "webinar"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "zoom",
      targetUrl: "https://zoom.us/",
      username: "",
      isDynamic: true,
    }),
  },

  // ==========================================
  // PRODUCTIVITY & CLOUD DOCS
  // ==========================================
  google_forms: {
    id: "google_forms",
    contentType: "platform_link",
    platform: "google_forms",
    label: "Google Form",
    shortDescription: "Collect survey responses, registrations, or event sign-ups.",
    category: "productivity",
    iconName: "CheckSquare",
    prefixUrl: "https://forms.gle/",
    placeholder: "form-code",
    keywords: ["form", "survey", "google forms", "registration"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "google_forms",
      targetUrl: "https://forms.gle/",
      username: "",
      isDynamic: true,
    }),
  },
  google_drive: {
    id: "google_drive",
    contentType: "platform_link",
    platform: "google_drive",
    label: "Google Drive",
    shortDescription: "Share shared folders, assets, or presentations on Google Drive.",
    category: "productivity",
    iconName: "Folder",
    prefixUrl: "https://drive.google.com/",
    placeholder: "drive/folders/...",
    keywords: ["drive", "cloud", "folder", "share"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "google_drive",
      targetUrl: "https://drive.google.com/",
      username: "",
      isDynamic: true,
    }),
  },
  slack: {
    id: "slack",
    contentType: "platform_link",
    platform: "slack",
    label: "Slack Community",
    shortDescription: "Invite team members or developer communities to your Slack.",
    category: "productivity",
    iconName: "Hash",
    prefixUrl: "https://join.slack.com/",
    placeholder: "t/workspace/...",
    keywords: ["slack", "community", "team", "chat"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "slack",
      targetUrl: "https://join.slack.com/",
      username: "",
      isDynamic: true,
    }),
  },

  // ==========================================
  // COMMERCE
  // ==========================================
  amazon: {
    id: "amazon",
    contentType: "platform_link",
    platform: "amazon",
    label: "Amazon Store / Product",
    shortDescription: "Link directly to storefront, product listing, or storefront ASIN.",
    category: "commerce",
    iconName: "ShoppingBag",
    prefixUrl: "https://amazon.com/dp/",
    placeholder: "ASIN-code",
    keywords: ["amazon", "shop", "ecommerce", "asin", "product"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "amazon",
      targetUrl: "https://amazon.com/",
      username: "",
      isDynamic: true,
    }),
  },
  etsy: {
    id: "etsy",
    contentType: "platform_link",
    platform: "etsy",
    label: "Etsy Shop",
    shortDescription: "Connect shoppers to handcrafted goods on your Etsy storefront.",
    category: "commerce",
    iconName: "Gift",
    prefixUrl: "https://etsy.com/shop/",
    placeholder: "shop-name",
    keywords: ["etsy", "handmade", "craft", "shop"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "platform_link",
      platform: "etsy",
      targetUrl: "https://etsy.com/shop/",
      username: "",
      isDynamic: true,
    }),
  },

  // ==========================================
  // PAYMENTS & FINTECH
  // ==========================================
  upi: {
    id: "upi",
    contentType: "payment",
    label: "UPI Payment (India)",
    shortDescription: "Scan with PhonePe, GPay, or Paytm to initiate instant UPI payment.",
    category: "payments",
    iconName: "CreditCard",
    keywords: ["upi", "india", "gpay", "phonepe", "paytm", "bhim", "vpa"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "payment",
      scheme: "upi",
      payeeAddress: "",
      payeeName: "",
      amount: undefined,
      currency: "INR",
      note: "",
    }),
  },
  paypal: {
    id: "paypal",
    contentType: "payment",
    label: "PayPal.Me",
    shortDescription: "Receive payments or donations via personal or business PayPal.",
    category: "payments",
    iconName: "DollarSign",
    prefixUrl: "https://paypal.me/",
    placeholder: "username",
    keywords: ["paypal", "payment", "donate", "money"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "payment",
      scheme: "paypal",
      payeeAddress: "",
      amount: undefined,
      currency: "USD",
      note: "",
    }),
  },
  venmo: {
    id: "venmo",
    contentType: "payment",
    label: "Venmo",
    shortDescription: "Quick peer-to-peer payments on Venmo.",
    category: "payments",
    iconName: "Send",
    prefixUrl: "https://venmo.com/",
    placeholder: "username",
    keywords: ["venmo", "pay", "money", "us"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "payment",
      scheme: "venmo",
      payeeAddress: "",
      amount: undefined,
      currency: "USD",
      note: "",
    }),
  },
  cashapp: {
    id: "cashapp",
    contentType: "payment",
    label: "Cash App ($Cashtag)",
    shortDescription: "Transfer funds directly through Cash App.",
    category: "payments",
    iconName: "DollarSign",
    prefixUrl: "https://cash.app/$",
    placeholder: "cashtag",
    keywords: ["cash app", "cashtag", "money"],
    supportsDynamic: true,
    supportsStatic: true,
    createDefault: () => ({
      type: "payment",
      scheme: "cashapp",
      payeeAddress: "",
      amount: undefined,
      currency: "USD",
      note: "",
    }),
  },
  pix: {
    id: "pix",
    contentType: "payment",
    label: "PIX (Brazil)",
    shortDescription: "Instant Brazilian central bank PIX key payment standard.",
    category: "payments",
    iconName: "CreditCard",
    keywords: ["pix", "brazil", "banco central", "chave"],
    supportsDynamic: false,
    supportsStatic: true,
    createDefault: () => ({
      type: "payment",
      scheme: "pix",
      payeeAddress: "",
      payeeName: "",
      amount: undefined,
      currency: "BRL",
      note: "",
    }),
  },
};

export const QR_TYPE_LIST = Object.values(QR_TYPE_REGISTRY);

/**
 * Filter registry types by category and search query.
 */
export function searchQrTypes(category: QrCategory = "all", query: string = ""): QrTypeDefinition[] {
  const q = query.trim().toLowerCase();

  return QR_TYPE_LIST.filter((t) => {
    // Category match
    if (category !== "all") {
      if (category === "quick_start") {
        const quickStartIds = ["url", "text", "wifi", "vcard", "instagram", "upi", "pdf", "app"];
        if (!quickStartIds.includes(t.id)) return false;
      } else if (t.category !== category) {
        return false;
      }
    }

    // Query match
    if (!q) return true;
    if (t.label.toLowerCase().includes(q)) return true;
    if (t.shortDescription.toLowerCase().includes(q)) return true;
    if (t.id.toLowerCase().includes(q)) return true;
    if (t.keywords.some((k) => k.toLowerCase().includes(q))) return true;

    return false;
  });
}
